### ISSUE TITLE
About your Hexagonal Architecture prototype & questions

### ISSUE THREAD

**Issue by tpierrain** [bertilmuth/requirementsascode#4]
Hi Bertil,

Here are my remarks about your prototype (https://github.com/bertilmuth/requirementsascode/tree/master/requirementsascodeexamples/hexagon/src/main/java/hexagon).

First, your left-side Adapter (i.e. [ConsoleAdapter](https://github.com/bertilmuth/requirementsascode/blob/master/requirementsascodeexamples/hexagon/src/main/java/hexagon/ConsoleAdapter.java)) must not reference the other right-side Adapters (i.e. WriterAdapter and RepositoryAdapter). The Hexagonal Architecture pattern describe a situation where:
 - All the business-logic must only be located within the hexagon
 - The right-side adapters must only be referenced/aggregated by the hexagon
 - The hexagon must only be referenced/aggregated by the left-side adapters
 - The application (e.g.: your controllers) knows and uses only the left-side adapters to interact with the business-logic embedded within the hexagon
 
Regarding your state management. You seem to delegate the business-logic state to your use case{Model|ModelBuilder|...} framework. I didn't have time to study the whole thing (with Steps, Flows, Actors, etc) but I'm wondering how you will handle the per-user state-machine.

 Anyway. For me the situation here with that UC framework goes a little way out our the Hexagonal Architecture pattern and I would suggest to let your use case "controller" out of the hexagon and making it only deal with the left-side Adapters you have.

---

Now, to answer your initial question: [where to put state dependent behavior? Say user gets happy poem first time she asks. 2nd time sad one. 3rd time another one](https://twitter.com/BertilMuth/status/879954971365691392) , I would suggest something like that:

1. The end-user send a "GiveMeSomePoetry" DTO/Command/Request through a left-side Adapter. Depending on the used technology (http stack, *MQ, etc), the adapter is aware of and capture the identity of the user in order to provide it to the [IRequestVerses](https://github.com/tpierrain/hexagonalThis/blob/master/HexagonalThis.Domain/IRequestVerses.cs).GiveMeSomePoetry(...) left-side port verb that must now accept one argument: the identity of the end-user (GiveMeSomePoetry(string userId) for instance)
2. The [PoetryReader](https://github.com/tpierrain/hexagonalThis/blob/master/HexagonalThis.Domain/PoetryReader.cs) hexagon (which implement this left-side port) will then ask a UserSessions instance (a new __Domain__ concept): "what was the last sentiment associated to the poem we had previously delivered to that end-user?". The answer to that question will help the PoetryReader business logic to decide what kind of poem it should ask to the Repository implementing the [IObtainPoem](https://github.com/tpierrain/hexagonalThis/blob/master/HexagonalThis.Domain/IObtainPoems.cs) right-side port. Of course, this one must be updated in order to provide 3 methods instead of one: getSadPoem(); getHappyPoem(); and getFunnyPoem();

Of course this is only one way to implement it (among many), you can also delegate the UsersSessions/state management to an external system for instance (to make it persistant even after a crash of your service). In that case, you will have to add a new right-side port/adapter for your hexagon business logic to be able to use it.

Hope it will clarify what we already discussed on twitter. Happy coding !

Thomas

**Comment by bertilmuth** [comment]
Hi Thomas. Thank you so much for taking the time to respond in detail. I will go through your comments one by one.

First, you write: "your left-side Adapter (i.e. ConsoleAdapter) must not reference the other right-side Adapters". 
I renamed it - it is what I call a "use case realization" now. I understand and fully support your statement: only the hexagon can call right side adapters. So in my view, the use case realization is part of the hexagon now.

The only confusing thing for me, that originally caused me to do it this way, is the following: in your talk, you actually "chain" adapters. You have the application, which is implicitly already an adapter, that calls your ConsoleAdapter (is that the right name?), that then calls the hexagon.

**Comment by bertilmuth** [comment]
You wrote: "I'm wondering how you will handle the per-user state-machine."
Every user gets an own instance of UseCaseModelRunner, that is configured by a UseCase Model. That is the "state machine" (sort of).

**Comment by bertilmuth** [comment]
You wrote: "That UC framework goes a little way out our the Hexagonal Architecture pattern and I would suggest to let your use case "controller" out of the hexagon and making it only deal with the left-side Adapters you have."

I agree with your second point: the framework only deals with left side adapters - the "ConsoleAdapter" was badly named. To be more precise: the UseCaseModelRunner only accepts events from the outside, and reacts accordingly.

**Comment by bertilmuth** [comment]
Concerning your first point: after rereading the original article by Alistair Cockburn, I would suggest the following. The article says: "The functional specification of the application, perhaps in use cases, is made against the inner hexagon’s interface and not against any one of the external technologies that might be used." 

That is exactly what I do - I make a functional specification in the form of use cases. At the interface of the inner hexagon. Inside the code. The article does not mention what level of use cases. My take is: user goal level use cases.

**Comment by bertilmuth** [comment]
So if user goal level use cases specify the interface of the inner hexagon, this has consequences for the interface.

For one, the interface of the inner hexagon specifies static method/function signatures.

On the other hand, as user goal level use cases specify flows, the **protocol** of the interface needs to be specified as well - what sequences of events the hexagon accepts, and how it reacts to each event.

This is how my framework works - your approach is fine as well, and I will not argue against it. If you are interested why I chose my approach, independent of the hexagonal architecture pattern, read on.

**Comment by bertilmuth** [comment]
If the interface of the inner hexagon, the boundary between inside and outside, "knows" the protocol, the inside of the hexagon does not need to know it. Based on my experience, I would claim that it can make the inside code easier to read, understand, test, potentially reduces dependencies etc. 

Also, the outside usually needs to "know" the protocol, that's why I expose it, explicitly.
That may not be obvious at first. But almost all user interfaces follow the protocol derived from the use cases. For example, a user interface enables and disables buttons, check boxes etc. based on the events that occured before. In short: the user interfaces reflect the use case flows!

In most application code I see, the flows of the use cases are encoded in the user interface code. But really, it is business logic! So if the inside of the hexagon (or any application business logic) checks for correct state / protocol adherence as well, you have a redundancy between user interface code and the business logic inside the hexagon.

In contrast, in my approach, the user interface code can simply ask the UseCaseModelRunner instance: are you willing to accept the user event XYZ now? And depending on the answer, the user interface can enable/disable buttons, for example. And it is the UseCaseModelRunner instance that makes the decision which page of the user interface to show. 

There is a single point of truth for the use cases: at the inner hexagon's boundary, in the use case model. And if the user interface changes, for example, the use case model can be reused, bringing all the flows etc. with it.

**Comment by bertilmuth** [comment]
There is one more reason why my framework explicitly represents the use case model: you can always generate textual documentation from the use case model. It is an executable, up-to-date specification of the actual behavior of the software.

**Comment by bertilmuth** [comment]
So, I hope reading this was interesting. And I am always thankful for feedback.

**Comment by bertilmuth** [comment]
So, I hope reading this was interesting. And I am always thankful for feedback.

**Comment by tpierrain** [comment]
Yes. That is clarifying things. Thanks for your explanations.
