### ISSUE TITLE
Java 8 compatibility question

### ISSUE THREAD

**Issue by doublefx** [bertilmuth/requirementsascode#78]
Hi,

I'm currently testing it and was wondering whether a Java 8 version of the lib could be found, at the moment, I get:

```
2020-07-21 08:38:56.798 ERROR 1752 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NoSuchMethodError: java.util.Optional.ifPresentOrElse(Ljava/util/function/Consumer;Ljava/lang/Runnable;)V
	at org.requirementsascode.ModelRunner.publishMessage(ModelRunner.java:53) ~[requirementsascodecore-1.7.jar:1.7]

```

**Comment by bertilmuth** [comment]
Hi Frédéric,
thank you for reporting this.
For a reason I can't reproduce, Gradle didn't pick this up, even though I set the compatibility to Java 8.
I will produce a 1.7.1 version that is compatible, and I would be glad if you could give me feedback if you could try it out.

**Comment by doublefx** [comment]
Might it be because in .travis.yml, there is:

jdk:
  - openjdk14
  - oraclejdk14

**Comment by doublefx** [comment]
Also, you might need to replace some code, for example, java.util.Optional.ifPresentOrElse() has been introduced in Java 9

**Comment by bertilmuth** [comment]
Concerning .travis.yml: 
I can't put JDK8 there, since one of the example subprojects uses JDK11.
Or is it possible to "overwrite" the travis.yml in a subproject? I'm not sure.

Yes, ifPresentOrElse() is the offender. I will replace it in 1.7.1, and I'll let you know once that's available to try out.

**Comment by bertilmuth** [comment]
The .travis.yml shouldn't influence the local Gradle build, though, and that passes, even though it specifies the compatibility to JDK8. Strange.

**Comment by doublefx** [comment]
In Gradle, have you tried:

apply plugin: 'java'
compileJava {
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
}

**Comment by bertilmuth** [comment]
Yes, I had it top level first and then made it part of the compileJava, exactly as you suggested.
Still didn't catch the incompatibility. I'll keep trying.

Anyway, v1.7.1 is now available.
Before I officially publish it: do you mind trying it out this time?
I'll keep looking at automating spotting these kinds of bugs in the future.

**Comment by doublefx** [comment]
Thanks @bertilmuth, I will try it today, I'll be back to you in few hours.

**Comment by doublefx** [comment]
Actually, I've already been able to test 1.7.1 on the simple code I currently have and it is all good.
I will keep testing this lib against real live code during this week and the next one, it looks like it could help us at producing some good quality code.

Thanks again @bertilmuth for having been that reactive, I'll keep you up to date on whether we adopt it or not.

**Comment by bertilmuth** [comment]
Hi @doublefx, thank you for reporting this!
You spotted a crucial weekness in my build process, this helps a lot.
I look forward to your feedback.

**Comment by bertilmuth** [comment]
I've released v1.7.1 and incorporated OpenJDK8 in the travis.yml now, so that these kinds of bugs don't appear again.

**Comment by doublefx** [comment]
Hi @bertilmuth 

Is there a way we can communicate thru chat, I'm struggling on some points?

**Comment by bertilmuth** [comment]
We can chat on Gitter ([here](https://gitter.im/requirementsascode/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link])).

**Comment by bertilmuth** [comment]
I just released v1.7.5 that addresses the issue that we talked about. Calling `modelRunner.reactTo()` from a method called by system now throws an exception. (#87)

**Comment by bertilmuth** [comment]
I answered you on Gitter.

The fist thing you should try is to replace the exception handling step with this:
.step(HANDLES_SYSTEM_EXCEPTION).on(process_order_exception).system(() -> modelRunner.stop())
if you have access to the modelRunner instance

You can reach me now at bertil@requirementsascode.org

**Comment by bertilmuth** [comment]
Send me a Skype invitation if you want to (we're using Teams)

**Comment by bertilmuth** [comment]
An even smaller step to try out, instead of replacing the exception handler line would be to comment it out.
This should still work. Why?

Because what you're doing is effectively catching and rethrowing the exception. You don't need that.
If some system reaction method returns an exception, it's already in the system.
The modelRunner returns the message published last.

**Comment by bertilmuth** [comment]
Here's a Gist that outlines a solution for your second example:
https://gist.github.com/bertilmuth/8ada55cf96633475a11bccb865cd077e

**Comment by bertilmuth** [comment]
By commenting it out above meant: comment out the whole exception handling flow

**Comment by bertilmuth** [comment]
Here's a second Gist that shows how to extract the publishing step:
https://gist.github.com/bertilmuth/702ba231e73137a796ff7870c2b42cac

**Comment by bertilmuth** [comment]
Roundtrip will be enabled in v1.7.6. Will release soon.
